NearNodeFlash/nnf-sos

- .github/workflows/main.yml
- Makefile
- Readme.md
- config/manager/kustomization.yaml
Signed-off-by: Anthony Floeder <anthony.floeder@hpe.com>
> Update IMAGE_NAME in makefile to match ghcr.io name

- controllers/nnf_node_storage_controller.go
This commit changes the NnfNodeStorage controller to read the FileShare
from swordfish before updating it. This prevents the FileSharePath from
being overwritten from its current value. This is necessary because the
FileShare resource is edited from both the NnfNodeStorage controller and
the ClientMount controller.
> RABSW-936: NnfNodeStorage controller maintains FileShare mount path

- config/rbac/role.yaml
- controllers/nnf_persistentstorageinstance_controller.go
The PersistentStorageInstance controller needs to delete the Servers resources
with deletecollection. Add to the RBAC rules.
> RABSW-939: Add deletecollection for servers

- controllers/integration_test.go
This commit adds some checks to make sure that the compute section of the
DirectiveBreakdown is populated correctly.
> RABSW-950: Add tests for DirectiveBreakdown computes

- api/v1alpha1/nnf_access_types.go
- config/crd/bases/nnf.cray.hpe.com_nnfaccesses.yaml
Print the status of an NnfAccess.
> RABSW-958 Add printcols for NnfAccess resources

- controllers/nnf_node_slc.go
- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/storage_types.go
- vendor/github.com/HewlettPackard/dws/controllers/clientmount_controller.go
- vendor/github.com/HewlettPackard/dws/mount-daemon/controllers/clientmount_controller.go
- vendor/modules.txt
All NNF drives have a WearLevel value - this must be used by the NNF Node SLC to report it via the DWS api.
> RABSW-947: Report drive WearLevel

- api/v1alpha1/nnfstorageprofile_types.go
- api/v1alpha1/nnfstorageprofile_webhook_test.go
- config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
- controllers/directivebreakdown_controller.go
> RABSW-973 Add MGT and MDT default capacity to NnfStorageProfile

- go.mod
- go.sum
- vendor/modules.txt
> RABSW-970: Vendor latest DWS

- controllers/nnf_workflow_controller.go
> RABSW-993 Add more DM-related logging to nnf_workflow_controller

- controllers/nnf_access_controller.go
Log clientmount create/update.
Add nnfstorage to lustre version of clientmount.
Allow non-NnfNodeStorage in client device reference.
> RABSW-995 client-initiated lustre-to-lustre data movement

- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_types.go
- vendor/github.com/HewlettPackard/dws/config/crd/bases/dws.cray.hpe.com_workflows.yaml
- vendor/github.com/HewlettPackard/dws/controllers/workflow_controller.go
- vendor/modules.txt
> RABSW-997 change workflow.status.reason to status.status

- controllers/nnf_node_controller.go
This subscribes the NNF Node to the NNF Event Manager, and for USP/DSP port events it will trigger a reconcile.
When nnf-ec initializes, a lot of events are generated. But because the NNF manger does not go "Enabled" until the fabric had a chance to initialize, these events are ignored in the Reconcile(). So there was not special handling needed for this burst of events.
The fabric manager polls the hardware every 60 seconds and generates change events. So the NNF Node should be updated at the same frequency
> NNF Node Controller: Maintain the resource with current port status

- Makefile
- config/default/manager_auth_proxy_patch.yaml
> Update kube-rbac-proxy to v0.13.0, to work on an M1.

- controllers/nnf_access_controller.go
- controllers/nnf_workflow_controller.go
This commit fixes a bug in the workflow reconciler where a NotFound error for an NnfAccess was treated as a success. This allowed the workflow to complete the pre_run phase when the client wasn't mounted. I also added code to pull the ResourceError information from the NnfNodeStorage into the NnfAccess when setting up the endpoints.
> nnf-sos #61: Don't ignore NotFound error for NnfAccess

- api/v1alpha1/nnf_datamovement_types.go
- controllers/integration_test.go
- controllers/nnf_workflow_controller.go
- controllers/nnf_workflow_controller_helpers.go
> Make DM teardown state label public

- controllers/directivebreakdown_controller.go
- controllers/nnf_access_controller.go
- controllers/nnf_persistentstorageinstance_controller.go
- controllers/nnf_storage_controller.go
- controllers/nnf_workflow_controller.go
- controllers/nnf_workflow_controller_helpers.go
- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/owner_labels.go
- vendor/github.com/HewlettPackard/dws/controllers/workflow_controller.go
- vendor/modules.txt
This is a proposal to return additional information for each start|finish state so the logs have more details as to _WHY_ waits and retries are occurring.
(this won't compile as is)
> Proposal for adding custom result to workflow start|finish states & dws object deletion code

- controllers/nnf_node_storage_controller.go
> EC errors from FS creation are fatal, and reconciliation should stop.

- controllers/nnf_servers_controller.go
The allocations listed in the status section of the Servers resource needs to be reset and rebuilt from the current nnfStorage/nnfNodeStorage data. The reset wasn't happening, so old allocation data was being set in the status.
> RABSW-948: Clear Servers status to prevent stale data

- Makefile
> Undeploy needs kustomize

- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_types.go
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_webhook.go
- vendor/github.com/HewlettPackard/dws/config/crd/bases/dws.cray.hpe.com_workflows.yaml
- vendor/github.com/HewlettPackard/dws/utils/updater/status_updater.go
- vendor/modules.txt
Pick up the latest DWS changes.
> RABSW-1016: Vendor DWS

- controllers/directivebreakdown_controller.go
- controllers/integration_test.go
- controllers/nnf_workflow_controller.go
- controllers/nnf_workflow_controller_helpers.go
- controllers/nnf_workflow_controller_test.go
- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha1/directivebreakdown_types.go
- vendor/github.com/HewlettPackard/dws/config/crd/bases/dws.cray.hpe.com_directivebreakdowns.yaml
- vendor/modules.txt
Verify that the allocations specified in the Servers resource match what was requested in the DirectiveBreakdown.
> RABSW-1079: Add validation checks to servers resource

- Makefile
> Remove 'test' prerequisite from docker-build target

- go.mod
- go.sum
- vendor/github.com/NearNodeFlash/nnf-ec/internal/switchtec/pkg/nvme/device_list.go
- vendor/github.com/NearNodeFlash/nnf-ec/internal/switchtec/pkg/nvme/nvme.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_pool.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_api.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_cli.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_device.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_direct_device.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_mock.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_mock_persistence.go
- vendor/modules.txt
> Update nnf-ec to latest master @ fcd6e4

- controllers/nnf_node_storage_controller.go
Fix for a bug introduced in the latest commit. Add the named return value and don't clobber an existing errors with the return value from Unmount().
> RABSW-1083: Fix error return from unmount

- go.mod
- go.sum
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-fabric/config_default.yaml
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/file_system_api.go
- vendor/modules.txt
> Upgrade nnf-ec to latest (dde289)

- go.mod
- go.sum
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
- vendor/modules.txt
Pulls in the latest nnf-ec which has the NNF Manager initialize the resource health to "Critical"
Fixes #109
> Update nnf ec to 0643bca

- controllers/integration_test.go
> Use the DWS workflowname vars for label names

- deploy.sh
> Ignore not found resource on undeploy

- controllers/directivebreakdown_controller.go
- controllers/nnf_servers_controller.go
- controllers/nnf_storage_controller.go
- controllers/nnf_workflow_controller_helpers.go
- controllers/nnf_workflow_controller_test.go
- go.mod
- go.sum
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/ec/error.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/file_system_lustre.go
- vendor/modules.txt
> RABSW-1081: Support multiple MDTs

- controllers/integration_test.go
- controllers/nnf_workflow_controller.go
- controllers/nnf_workflow_controller_helpers.go
- controllers/nnf_workflow_controller_test.go
> Refactor Job/Persistent directive references to use "DW" prefix

- config/samples/nnf_v1alpha1_nnfstorageprofile.yaml
- config/samples/placeholder_nnfstorageprofile.yaml
> Fix for 'lockStart' typo

- .github/workflows/main.yml
I'm using `feature/containers` and would like to ensure PR to that branch are building.
> Added  PR builds for feature branches

- controllers/nnf_node_storage_controller.go
> Shorten LVM names

- controllers/nnf_workflow_controller.go
- controllers/nnf_workflow_controller_helpers.go
Also use Create instead of CreateOrUpdate for Container Jobs/Service
> Mount container storages into containers via volumes

- config/dws/nnf-ruleset.yaml
> Ensure 'key' values in the ruleset match against the exact string

- main.go
Keep the one for the SLC, remove the one in main().
> main.go has too many calls to controllers.NnfPortManagerReconciler

- config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml
- deploy.sh
Wait for the DWS webhook to be ready when doing a fresh deploy.
Update an out of date CRD.
> Wait for DWS webhook

- Makefile
- controllers/nnf_systemconfiguration_controller.go
- controllers/nnf_systemconfiguration_controller_test.go
- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha2/systemconfiguration_types.go
- vendor/modules.txt
And use the StatusUpdater to do so.
> Set SystemConfiguration to Ready:true

- controllers/nnf_workflow_controller_helpers.go
> Container volumes: convert underscores to hyphens

- controllers/nnf_workflow_controller_helpers.go
- go.mod
- go.sum
- vendor/github.com/HewlettPackard/dws/api/v1alpha2/workflow_types.go
- vendor/modules.txt
Use the routines provided by DWS.
> Translate a ResourceError severity to a Workflow status

- internal/controller/nnf_workflow_controller_test.go
> Added tests for bad copy_out directives

- pkg/command/cmd.go
> Add RunAs/RunAsWithTimeout to allow commands as UID/GID

- internal/controller/nnf_workflow_controller_container_helpers.go
> Fix issue with MPI worker hostnames

- go.sum
- internal/controller/nnf_access_controller.go
- internal/controller/nnf_clientmount_controller.go
- internal/controller/nnf_node_block_storage_controller.go
- internal/controller/nnf_workflow_controller.go
- pkg/blockdevice/lvm.go
- pkg/blockdevice/lvm/lvs.go
- pkg/blockdevice/lvm/vgs.go
- pkg/blockdevice/lvm/volume_groups.go
- Wait for VG to show up in the OS before trying to lock it
> - vgs/lvs commands avoid locking

- config/rbac/clientmount_role.yaml
- internal/controller/nnf_clientmount_controller.go
The clientmountd does in fact reference NnfStorageProfiles.
> Revert commit 95a3e12593

- internal/controller/nnf_systemconfiguration_controller.go
On a large system we do not want the time & traffic hit that comes with deleting namespaces.
> SystemConfiguration controller should not delete namespaces

- config/manager/kustomization.yaml
- internal/controller/nnf_node_block_storage_controller.go
- internal/controller/nnf_storage_controller.go
> Release v0.1.9

- internal/controller/nnf_node_block_storage_controller.go
The deletion path of the NnfNodeBlockStorage only deletes StoragePools if the StoragePoolId field was populated in the Status section. If the status section wasn't able to be updated, we still need to delete the StoragePools. This change tries to delete all the StoragePools the could have been created by an NnfNodeBlockStorage regardless of what the Status section contains.
> Try to delete all StoragePools on NnfNodeBlockStorage deletion

- internal/controller/nnf_access_controller.go
- internal/controller/nnf_storage_controller.go
For errors that come from the NnfNodeBlockStorage, NnfNodeStorage, or ClientMount, prefix the error with the name of the node that it came from. This helps with debugging issues after the workflow has been deleted.
> Prefix errors with Rabbit/Compute node name

- api/v1alpha1/nnfdatamovementprofile_types.go
- config/crd/bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml
- config/examples/nnf_v1alpha1_nnfdatamovementprofile.yaml
> nnf-dm: allow mkdir to be configurable via profiles

- go.mod
- go.sum
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/clientmount_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/computes_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/directivebreakdown_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/dwdirectiverule_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/persistentstorageinstance_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/servers_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/storage_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/systemconfiguration_webhook.go
- vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/workflow_webhook.go
- vendor/github.com/NearNodeFlash/lustre-fs-operator/api/v1beta1/lustrefilesystem_webhook.go
- vendor/modules.txt
Part of the release process.
Dean's tool kicking in.
> Update peer modules

- api/v1alpha1/nnfcontainerprofile_webhook.go
- api/v1alpha1/nnfdatamovementprofile_webhook.go
- api/v1alpha1/nnfstorageprofile_webhook.go
- api/v1alpha1/webhook_suite_test.go
- cmd/main.go
Minimize the diffs we have as we go forward.
> Incorporate some differences from a more recent kubebuilder version.

- api/v1alpha1/nnfdatamovementprofile_types.go
- config/crd/bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml
- config/examples/nnf_v1alpha1_nnfdatamovementprofile.yaml
> NnfDataMovementProfile: add statCommand

- api/v1alpha1/nnfcontainerprofile_types.go
- api/v1alpha1/nnfcontainerprofile_webhook_test.go
- config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
> Increase container timeouts to 5m

- PROJECT
These are confusing the crd-bumper tool.
> Remove stale elements from PROJECT

- mount-daemon/main.go
> clientmountd: use nnfv1alpha2

- cmd/main.go
- config/dp0/manager_volumes_patch.yaml
- go.mod
- go.sum
- internal/controller/nnf_node_block_storage_controller.go
- internal/controller/nnf_node_controller.go
- internal/controller/suite_test.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/controller.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/ec/ec.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/allocation_policy.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_pool.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
- vendor/modules.txt
Vendor the latest nnf-ec and supply the `deleteUnknownVolumes` cli parameter.
> Add deleteUnknownVolumes cli parameter to nnf-ec

- internal/controller/nnf_workflow_controller.go
Data Movement nightly tests routinely hit this issue:
https://github.com/NearNodeFlash/NearNodeFlash.github.io/issues/161.
This appears to only affect a specific version of lustre/toss on our system until
we upgrade.
This change adds an optional workaround for to add a pause to let lustre
settle after mounting. 1s appears to be all that is needed.
> Add env var for optional pause during DataIn

- config/manager/kustomization.yaml
- go.mod
- go.sum
- internal/controller/nnf_workflow_controller.go
- vendor/modules.txt
> Release v0.1.15

- config/rbac/api_priority_and_fairness_role.yaml
Save the working rules so they can be found quickly some other day.
> Role rules to monitor API Priority and Fairness

- internal/controller/nnf_systemconfiguration_controller.go
- internal/controller/nnf_systemconfiguration_controller_test.go
A rabbit that has lost its NoSchedule taint, but retains its nnf.cray.hpe.com/taints_and_labels_completed=true label, was not able to repair its taints.
This change allows the nnf_systemconfiguration_controller to examine the node and determine whether the label is stale with respect to the state of the taints, and to correct the taints if necessary.
> Add ability repair the state of the NoExecute/NoSchedule taints

- PROJECT
This is cruft that is confusing the collect-manifests tool.
> Remove dataworkflowservices from PROJECT

- internal/controller/nnf_workflow_controller_container_helpers.go
When there are multiple containers defined in a podSpec,
an initContainer is added for each one.
This makes sure this is only done once.
> MPIJob: Run /etc/passwd initContainer only once

- config/rbac/kustomization.yaml
Rearrange the parts, maybe this will save conversion-gen from breaking it again.
> Fix rbac kustomization

- config/dp0/manager_volumes_patch.yaml
- go.mod
- go.sum
- internal/controller/nnf_node_block_storage_controller.go
- internal/controller/nnf_node_controller.go
- vendor/github.com/NearNodeFlash/nnf-ec/internal/switchtec/pkg/nvme/nvme.go
- vendor/github.com/NearNodeFlash/nnf-ec/internal/switchtec/pkg/switchtec/events.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/controller.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-message-registry/registries/Nnf.1.0.0.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-message-registry/registries/Nnf.1.0.0.json
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/aer.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/allocation_policy.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/api.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/router.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/servicer.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_group.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_pool.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/nvme_mock.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/rfsf/pkg/models/model_storage_controller_v1_0_0_nv_me_controller_attributes.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/rfsf/pkg/models/model_storage_controller_v1_0_0_nv_me_controller_properties.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/rfsf/pkg/models/model_storage_controller_v1_0_0_nv_me_smart_critical_warnings.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/rfsf/pkg/models/model_storage_controller_v1_0_0_storage_controller.go
- vendor/modules.txt
Add command line parameter to trigger storage pool namespace replacement after drives are replaced
> Vendor latest nnf-ec

- config/manager/kustomization.yaml
- config/rbac/workload_manager_nnf_role.yaml
> Release v0.1.22

- config/manager/kustomization.yaml
- crd-bumper.yaml
- go.mod
- go.sum
- internal/controller/nnf_node_block_storage_controller.go
- internal/controller/nnf_workflow_controller_helpers.go
- pkg/helpers/helpers.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-message-registry/registries/Nnf.1.0.0.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-message-registry/registries/Nnf.1.0.0.json
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_pool.go
- vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
- vendor/modules.txt
> Release v0.1.23

- config/examples/nnf_nnfcontainerprofiles.yaml
- config/manager/kustomization.yaml
- go.mod
- go.sum
- internal/controller/nnf_access_controller.go
- internal/controller/nnf_workflow_controller_container_helpers.go
- internal/controller/nnf_workflow_controller_helpers.go
- vendor/modules.txt
> Release v0.1.24

- internal/controller/nnf_access_controller.go
- internal/controller/nnf_clientmount_controller.go
Add log messages to indicate when a compute node doesn't see the expected NVMe devices, and print the serial number and namespace ID.
Also, add some debug messages to show when a ClientMount is skipped because it has been marked as Disabled in the SystemStatus resource.
> Add NVMe debug

- internal/controller/nnf_node_storage_controller.go
Wait to add the NnfNodeStorage finalizer to the NnfNodeBlockStorage until it's ready, and don't try to teardown anything in the NnfNodeStorage if the NnfNodeBlockStorage doesn't have the NnfNodeStorage finalizer. This situations signifies that the NnfNodeBlockStorage was never successfully completed before teardown, and there are no file systems that need to be removed.
> Don't add finalizer to NnfNodeBlockStorage until it's ready

- config/manager/kustomization.yaml
- go.mod
- go.sum
- pkg/blockdevice/lvm.go
- vendor/modules.txt
> Release v0.1.27
