NearNodeFlash/nnf-sos

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_test.go
go.mod
go.sum
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/server_local.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/server_mock.go
vendor/modules.txt

- Do not create nnfaccess for lustre fs
- Delete nnfaccess on cleanup of data-movement instead of just unmount

Fixes found during data movement testing

---

config/rbac/role.yaml
controllers/nnf_access_controller.go
go.mod
go.sum
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/persistent.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/storage_group.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/file_system_lvm.go
vendor/modules.txt

- NNF Access is failing the DeleteAllOf call for Client Mounts because it's missing the `deletecollection` permission
- update nnf-ec to the latest and greatest

Fix delete collection / update nnf-ec

---

go.mod
go.sum
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/file_system_lustre.go
vendor/modules.txt

Use all of the provided devices when creating zpools for lustre targets.

RABSW-933 nnf-ec: use all devices when creating zpools

---

controllers/directivebreakdown_controller.go
controllers/integration_test.go
controllers/nnf_persistentstorageinstance_controller.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
controllers/nnfstorageprofile_helpers.go
controllers/nnfstorageprofile_test.go

This commit changes the ownership of the pinned profiles. Pinned profiles
are owned by either:
- The DirectiveBreakdown for jobdw
- The PersistentStorageInstance for create_persistent
The pinned profiles do not change ownership after they've been created.
I had to disable a few of the storage profile tests because we don't have the path
to bring errors from the DirectiveBreakdown into the Workflow.

RABSW-956: Change pinned profile ownership

---

controllers/nnf_access_controller.go
controllers/nnf_servers_controller.go
controllers/nnf_storage_controller.go

ListOptions doesn't honor multiple MatchingLabels. Create a single MatchingLabels
map with all the labels we want to match on.

RABSW-971: Fix multiple match labels

---

controllers/nnf_storage_controller.go

The NnfNodeStorage status aggregator uses a List() operation to find all the
NnfNodeStorage resources that are part of an allocation set. Depending on the
state of the client cache, we may miss some of the resources. This commit adds
a check to make sure we've found the expected number of resources.

RABSW-968: Verify NnfNodeStorage count when aggregating status

---

controllers/integration_test.go
controllers/nnf_access_controller.go

Nnf_access_controller needs the MGS NID of an orchestrated lustre filesystem
when creating the ClientMount resource. Sometimes that filesystem is using an
external MGS.

RABSW-981  recognize the use of externalMgs

---

config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml
controllers/nnf_access_controller.go
controllers/nnf_workflow_controller.go

This commit fixes two issues related to unmounting XFS and GFS2 filesystems
from the client:
- The workflow controller wasn't waiting for the NnfAccess to have a state of
"Unmounted" and "Ready" before deleting the NnfAccess.
- The NnfAccess controller was removing the compute node PCIe mappings before
deleting the ClientMount resources. If the ClientMounts were still mounted,
then clientmountd would give an error.

RABSW-991: Fix XFS/GFS2 unmount bug

---

api/v1alpha1/workflow_helpers.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

Move directiveIndexLabel from controllers/ to api/ and make it exported.  Then
the nnf-dm daemon will be able to use it.

RABSW-994 Export directiveIndexLabel from nnf-sos for nnf-dm

---

controllers/directivebreakdown_controller.go
controllers/directivebreakdown_controller_test.go
controllers/nnf_access_controller.go
controllers/nnf_clientmount_controller.go
controllers/nnf_node_slc.go
controllers/nnf_node_storage_controller.go
controllers/nnf_persistentstorageinstance_controller.go
controllers/nnf_storage_controller.go
controllers/nnf_systemconfiguration_controller.go
controllers/nnf_workflow_controller.go

The DirectiveBreakdown controller was relying on garbage collecting to delete
children. Use the DeleteChildren() call to delete them explicitly.

RABSW-987: Delete DirectiveBreakdown children explicitly

---

api/v1alpha1/workflow_error.go
controllers/integration_test.go
controllers/nnf_node_controller.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
go.mod
go.sum
vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_types.go
vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_webhook.go
vendor/github.com/HewlettPackard/dws/config/crd/bases/dws.cray.hpe.com_workflows.yaml
vendor/github.com/HewlettPackard/dws/controllers/workflow_controller.go
vendor/modules.txt

This commit uses the new string constants for the workflow driver
array status field.

RABSW-999: Use constants for driver status

---

api/v1alpha1/nnf_storage_types.go
config/crd/bases/nnf.cray.hpe.com_nnfstorages.yaml
controllers/nnf_storage_controller.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_test.go

This commit finds the error string in the NnfNodeStorageConditions array
and passes it through the NnfStorage to end up in the workflow.

RABSW-999: Collect error string from NnfNodeStorage

---

controllers/nnf_clientmount_controller.go

This commit changes the error path in the clientmount controller running on the
Rabbit node. If there is an error the Ready field is set to false regardless
of whether the mount/unmount had succeeded before.

RABSW-1005: Set Ready=false in clientmount after error

---

controllers/directivebreakdown_controller.go
controllers/metrics/metrics.go
controllers/nnf_access_controller.go
controllers/nnf_clientmount_controller.go
controllers/nnf_node_controller.go
controllers/nnf_node_ec_data_controller.go
controllers/nnf_node_storage_controller.go
controllers/nnf_persistentstorageinstance_controller.go
controllers/nnf_servers_controller.go
controllers/nnf_storage_controller.go
controllers/nnf_systemconfiguration_controller.go
controllers/nnf_workflow_controller.go
go.mod
vendor/modules.txt

Add some basic seed metrics to the operators,  to act as a pattern for others
to follow.

RABSW-1004 Add metrics support to the operators

---

api/v1alpha1/nnf_datamovement_types.go

This is to support Cancel for the Copy Offload API in nnf-dm.

Added Cancel Reason for Data Movement

---

controllers/nnf_workflow_controller.go

Verify that the allocations specified in the Servers resource by the WLM satisfy
the requirements of the DirectiveBreakdown.

RABSW-1006: Add verification to Servers resource inputs

---

Makefile

The v2 fail-fast flag has to be switched to the v1 failFast flag.

Revert to Ginkgo V1.

---

rabbit-os-mods/nnf-ec.sh

Signed-off-by: Anthony Floeder <anthony.floeder@hpe.com>

Fixes #65 - lvm settings must disable only udev_sync

---

controllers/nnf_workflow_controller.go

This commit changes the string that is used for the lustre fsname. Instead of using the "name" field in the #DW line, this commit uses the first 8 characters of the UID of the servers resource.

Change fsname for Lustre (#68)

---

.vscode/launch.json
api/v1alpha1/nnf_node_types.go
config/crd/bases/nnf.cray.hpe.com_nnfnodes.yaml
controllers/nnf_node_controller.go
controllers/nnf_node_slc.go
go.mod
go.sum
vendor/github.com/HewlettPackard/dws/api/v1alpha1/storage_types.go
vendor/github.com/HewlettPackard/dws/config/crd/bases/dws.cray.hpe.com_storages.yaml
vendor/github.com/NearNodeFlash/nnf-ec/pkg/api/fabric.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-fabric/config.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-fabric/config_default.yaml
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-fabric/manager.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/rfsf/pkg/common/alias.go
vendor/modules.txt

Each new field is sourced from the `StorageController`'s corresponding field.
In the case of `slot`, it is a concatenation of the `StorageController`'s `Location` field. The `SeviceLabel` and `LocationOrdinalValue` are put together. These two fields are sourced from the StorageController's config file - see nnf-ec for more details.
For example, with a label of `J` and ordinal value of `12`, the resulting `slot` is `J12`.

Added SerialNumber, FirmwareVersion, and Slot to NnfDriveStatus

---

controllers/nnf_workflow_controller_helpers.go

One of the helper functions was assuming that the index of the directiveBreakdown was the same as the index of the directive in the #DW list. That doesn't have to be the case and leads to a panic.

RABSW-984: Fix directive index to name/namespace mapping

---

controllers/nnf_storage_controller.go
controllers/nnf_workflow_controller_helpers.go

This commit fixes two bugs:
- The file system name in the nnfStorage is used as the Lustre fsname. This needs to start with a letter to satisfy Lustre's requirements.
- Errors in the nnfNodeStorage that eventually recover still show up as an error in the nnfStorage. The error is properly cleared out now.

RABSW-1015: Ensure fsname starts with a letter and fix error propagation

---

api/v1alpha1/nnfstorageprofile_types.go
api/v1alpha1/nnfstorageprofile_webhook.go
api/v1alpha1/nnfstorageprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
config/samples/nnf_v1alpha1_nnfstorageprofile.yaml
controllers/directivebreakdown_controller.go

Add a field named "exclusiveMdt" to the storage profile to indicate that the MDT must be marked in the directive breakdown as being the only lustre target on its server.
This is similar to the way an MGT is marked in the directive breakdown.

Allow a colocation constraint to be specified for an MDT.

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
go.mod
go.sum
vendor/modules.txt

Change the path for the client mounts to use a combination of the workflow UID and the directive index. This keeps each mount path unique while being easy to remove after unmount since there aren't any shared parent directories other than /mnt/nnf.

RABSW-1055: Use workflow UID for client mounts

---

config/dws/nnf-ruleset.yaml
controllers/directivebreakdown_controller.go
controllers/integration_test.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnfstorageprofile_helpers.go

Combined_mgtmdt and external_mgs can be specified in the storage profile. Removing these options from the directive allows the admins to have greater control of what end users can and cannot do.
Signed-off-by: Matt Richerson <matthew.richerson@dhcp-10-113-10-52.its.hpecorp.net>

RABSW-1086: Remove combined_mgtmdt and external_mgs directive arguments

---

controllers/nnf_node_storage_controller.go

Don't batch the updates until everything succeeds or there's a failure. This makes it hard to debug issues where there was a hang in nnf-ec. Update the status section after each nnf-ec operation.

RABSW-1094: Update NnfNodeStorage status after each nnf-ec operation

---

api/v1alpha1/nnf_node_types.go
config/crd/bases/nnf.cray.hpe.com_nnfnodes.yaml
controllers/nnf_node_controller.go

- Ensure the NNF Node `status.status` field is "Starting" at start of day
- Ensure the NNF Node `status.status` and `status.health` fields reflective of the current NNF Storage Service values while it is initializing
- Clean up some rookie error handling mistakes in the NNF Node `Start()` routine
- Add some default conflict retry in updating the NNF Node in the `Start()` routine. I have never observed this but it's likely safer than the current implementation
- Add the associated Pod name to NNF Node's default printcolumns

Fix for the NNF Node Status reporting 'Ready' when not ready

---

config/rbac/kustomization.yaml
config/rbac/kustomizeconfig.yaml
config/rbac/service_account.yaml

This creates a secret for managing nnf-sos resources; useful to the NNF Fencing agent
A similar change was made to dws and nnf-dm
Use it to grab token and cert like so
```bash
#!/bin/bash
SECRET=${1:-nnf-controller-manager}
NAMESPACE=${2:-nnf-system}
kubectl get secret ${SECRET} -n ${NAMESPACE} -o json | jq -Mr '.data.token' | base64 --decode > ./service.token
kubectl get secret ${SECRET} -n ${NAMESPACE} -o json | jq -Mr '.data["ca.crt"]' | base64 --decode > ./service.cert
```

Add known controller-manager secret

---

controllers/nnf_node_ec_data_controller.go

The unit test code doesn't sufficiently create the EC Data resource for each "node" in the system, so using it entirely by unit test is a problem.
Matt hit an error with the latest nnf-ec ; this will resolve that.

EC Data Controller StorageProvider for unit tests

---

api/v1alpha1/nnfcontainerprofile_types.go
api/v1alpha1/workflow_helpers.go
config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
config/dws/nnf-ruleset.yaml
config/manager/manager.yaml
config/samples/nnf_v1alpha1_nnfcontainerprofile.yaml
controllers/nnf_workflow_controller_helpers.go
controllers/nnfcontainerprofile_helpers.go

These changes allow a user to create a container workflow and have it go ready in the `Proposal` state. It validates that:
- the supplied container profile exists
- if any non-optional storage in the container profile exists, ensure it is present in the supplied arguments to the container directive
- any supplied storage argument in the container directive must exist in the container profile
In order to support validation of the `container` directive, the `NnfStorageProfile` pinning and default functionality has been duplicated and refactored for `NnfContainerProfile`. Ideally in the future, we combine the two.
The following directives were used to test this container workflow:
```
#DW jobdw name=blake-gfs2 type=gfs2 capacity=50GB
#DW persistentdw name=blake-persistent
#DW container …
```

RABSW-1107: Add container directive validation

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

Do some more sanity checks on staging directives:
- Don't allow staging to/from raw allocations
- Match allocation directives based on name and command "jobdw/persistentdw" since names can collide between the two types.

RABSW-1122: Don't allow staging to Raw allocations

---

.github/workflows/main.yml
.github/workflows/verify_tag.yml

Loosen the branch filter for pushes.
Print some event context, for future debugging.
Remove an unused variable from verify_tag.
Rename some jobs to give them unique names, to help with debugging.

Allow builds on all branches.

---

api/v1alpha1/nnf_access_types.go
config/crd/bases/nnf.cray.hpe.com_nnfaccesses.yaml
controllers/integration_test.go
controllers/nnf_access_controller_test.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

The data movement code was mounting and unmounting the Rabbit nodes during the DataIn and DataOut phases of the workflow. A stale workflow resource in the client cache could cause the NnfAccess to be re-mounted after it had already been unmounted. This commit changes the NnfAccess Teardown state logic to do the unmounts in PreRun and Teardown instead of DataIn and DataOut.

RABSW-1124: Change NnfAccess TeardownState for servers

---

api/v1alpha1/nnfcontainerprofile_types.go
config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
config/dws/nnf-ruleset.yaml
config/rbac/role.yaml
config/samples/nnf_v1alpha1_nnfcontainerprofile.yaml
controllers/directivebreakdown_controller.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

Jobs/pods are now being deployed and you can get through all of the workflow stages. The only exception is that PostRun won't go ready if jobs are still running while you transition. The completion logic is still a work in progress.
There are a lot of TODOs littered throughout, but here are the main milestones:
- Added container job deployment to the PreRun stage
- Added headless service deployment
- Jobs/Pods are now deployed to rabbits attached to the supplied compute nodes via the Workflow's Computes resource
- Added first attempt at completion logic to the PostRun stage
- Updated nnfcontainerprofile with development options to control job completion logic
- Update sample container profile to run a job that randomly exits pass/fail
- Jobs/pods/service are removed when the workflow is …

Add jobs and service deployment for containers

---

config/kind/kustomization.yaml
config/kind/manager_volumes_patch.yaml
controllers/nnf_access_controller.go
controllers/nnf_clientmount_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
main.go

Create empty directories on the Rabbit nodes in the clientmount reconciler to better fake out data movement and user containers.

RABSW-1128: Make fake mounts on kind Rabbit nodes

---

controllers/dws_storage_controller.go

I introduced a bug in #126 that prevents the DWS Storage resource from deleting because nnf-sos is undeployed before dws; thereby removing the controller pods that could have removed the storage resource finalizer.
The quick solution is to remove the finalizer on the resource.

Remove finalizer on the new DWS Storage Controller

---

controllers/nnf_clientmount_controller.go
go.mod
go.sum
vendor/github.com/HewlettPackard/dws/api/v1alpha1/workflow_webhook.go
vendor/github.com/HewlettPackard/dws/config/webhook/kustomization.yaml
vendor/github.com/HewlettPackard/dws/config/webhook/service.yaml
vendor/github.com/HewlettPackard/dws/config/webhook/service_account.yaml
vendor/github.com/HewlettPackard/dws/controllers/clientmount_controller.go
vendor/github.com/HewlettPackard/dws/utils/dwdparse/dwdparse.go
vendor/modules.txt

In the ClientMount controller for kind nodes, check whether the directory exists before creating or removing it.
Re-vendor dws

RABSW-1139: Fix ClientMount directory create/remove for kind environment

---

controllers/nnf_workflow_controller_helpers.go

- Replace any hyphens in the storage names with underscores
- Add in hostname, subdomain, and domain variables
Full list added to the container:
```yaml
$ kubectl get pod blake-container-kind-worker2-g7nqn -oyaml | yq '.spec.containers[].env'
- name: DW_JOB_foo_local_storage
value: /mnt/nnf/b696c436-fa56-4033-a26d-5063de8b84b8-0
- name: DW_PERSISTENT_foo_persistent_storage
value: /mnt/nnf/b696c436-fa56-4033-a26d-5063de8b84b8-1
- name: NNF_CONTAINER_SUBDOMAIN
value: blake-container
- name: NNF_CONTAINER_DOMAIN
value: default.svc.cluster.local
- name: NNF_CONTAINER_HOSTNAMES
value: kind-worker2 kind-worker3
```
Verified this by running a container with a script that attempts to use the env vars. This also verifies that the services is working with DNS:
```bash
sleep 3
for i in …
```

Add environmental variables

---

controllers/nnf_node_storage_controller.go

I'm thinking this is just a Part 1 - I really should be adding retryable error handling to all nnf-ec objects handling. Which means a function would be handy.
But this also introduces a problem - what if the Retryable occurs for ever (as currently happening on rabbit-node-1); Do we need a Retry Limit? Would it be time based, count based?

Handle Retryable EC errors for File Share

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

This change only lets PreRun go to Ready if the container jobs/pods have successfully started. A container could get stuck in the creation state (i.e. not running) for a number of reasons.
Tested by trying to mount a volume with a hostPath that doesn't exist, which causes the Containers to get stuck.

Wait for Container pods to start before going PreRun:Ready

---

api/v1alpha1/nnfcontainerprofile_types.go
config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
config/samples/nnf_v1alpha1_nnfcontainerprofile.yaml
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

PostRun will go `Ready:true` only if all jobs/pods have finished successfully. If containers are still running, PostRun requeues every 2 seconds until the jobs/containers have indicated a finish (pass or fail).
Once containers have finished, the results are checked. If all jobs are successful, then PostRun goes `Ready:true`. If not, then it stays `Ready:false`. Jobs are successful when a child pod has completed successfully (i.e. exited non-zero).
Additionally, a check now occurs when creating `NnfAccesses` for the rabbits to see if the `NnfAccess` is referenced by a container directive. If so, the `teardownState` is set to Teardown to ensure that mounts are present during the potential life of the containers through the PostRun state. This case only occurs during the PostRun state when a …

PostRun Ready Logic

---

config/examples/nnf_v1alpha1_nnfcontainerprofiles.yaml
config/samples/nnf_v1alpha1_nnfcontainerprofile.yaml
controllers/nnf_workflow_controller.go

A few changes to aid in running int-test at containers. Updated the sample profile with some documentation. Removed the container empty block from teardown.
This will be the last PR against the feature branch.
I used these changes to write container tests for int-test. Those changes will be coming after I merge the feature branch.

Prepare container profiles for int-test

---

config/samples/placeholder_nnfstorageprofile.yaml
controllers/nnf_node_storage_controller.go

This commit fixes two issues that were affecting gfs2 file systems:
- The dlm lock manager was failing to lock because the VG name was too long
- The lvcreate command needs an "--activate ys" to active a shared volume

github-151: Fix LVM issues with gfs2

---

config/examples/nnf_v1alpha1_nnfcontainerprofiles.yaml

Deployment of nnf-sos in non-kind environments throw an error if retryLimit is not present. I will probably make this field optional in the future.

Make sure example container profiles contain retryLimit

---

controllers/nnf_workflow_controller_helpers.go

This uses SecurityContext and inherits the Workflow's user/group ID.

Containers: Add non-root support

---

controllers/nnf_workflow_controller_helpers.go

These filesystems can only be mounted once - they are not supported for
containers.

Containers: Check for XFS/Raw filesystems

---

config/rbac/fencing_agent_role.yaml
config/rbac/fencing_agent_role_binding.yaml
config/rbac/fencing_agent_service_account.yaml
config/rbac/kustomization.yaml

Create a ServiceAccount for the NNF fencing agent that allows read and write access to Node and NnfNode resources.

RABSW-1150: Add ServiceAccount for NNF fencing agent

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

A few situations where being reported as errors when they should not be:
Job creation loop. Since the job is being reused for each rabbit node and with the possibility of updating the job, make sure the pod selector is empty. Do this by making sure the job structure for creating new jobs is fresh by doing DeepCopy. See more here:
https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-selector
Job container volumes: If the NNFAccess mount is not ready, requeue rather than return an error.
Job container start: It's possible that while waiting for the job containers to start, the jobs themselves don't exist or aren't queryable yet. Requeue.

Containers: Fix Error Output

---

controllers/suite_test.go

In the kubebuilder book:
https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html It explains that we should be using the "live" k8s client rather than the one from the manager:
"Note that we set up both a “live” k8s client and a separate client from the manager. This is because when making assertions in tests, you generally want to assert against the live state of the API server. If you use the client from the manager (k8sManager.GetClient), you’d end up asserting against the contents of the cache instead, which is slower and can introduce flakiness into your tests."

Use the live k8s client object in suite_test.go.

---

controllers/nnf_access_controller.go

This commit separates out the logic for mounting and unmounting an NnfAccess. This was to provide proper unlocking of the NnfStorage for XFS and raw allocations.

Github #39: Separate NnfAccess mount/unmount code paths

---

deploy.sh

The deploy.sh was looking for a "1/1" ready field for the dws webhook. There may not be enough worker nodes on the system to run all 3 DWS webhooks, so some of the webhook pods may not be ready. If one of these pods shows up first in the pod list, then the deploy.sh script will hang forever. Instead, look at the number of ready replicas in the dws webhook deployment to be one or more.

RABSW-1159: Update deploy.sh to look at the deployment ready count

---

config/manager/manager.yaml
go.mod
go.sum
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-server/file_system_api.go
vendor/modules.txt

Make use of the new timeout in nnf-ec when running commands. Timeout commands after 90 seconds and return an error.

RABSW-1158: Update nnf-ec and add timeout environment variable

---

config/dws/nnf-ruleset.yaml
config/examples/nnf_v1alpha1_nnfcontainerprofiles.yaml
config/manager/kustomization.yaml
config/samples/nnf_v1alpha1_nnfcontainerprofile.yaml
controllers/integration_test.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
controllers/nnfcontainerprofile_test.go

Restrict the name of the storage to something that can also be used as the name of a k8s resource.  This means the name must be made up of lowercase letters, numbers, and dashes.
When using that name in a DW_JOB_ or DW_PERSISTENT_ environment variable, swap the dashes for underscores in the storage name.

Restrict the name of the storage

---

Makefile
config/manager/manager.yaml

This should just go to an available untainted worker node.

Remove reliance on cray.nnf.manager node label.

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go

The alpine:latest container does not have a 'bash' executable.
Add some logging to indicate when the MPIJob or Job has been created.

Use sh rather than bash in init containers

---

config/manager/manager.yaml

This is to be consistent with the removal of these limits for nnf-dm, which were causing overhead during mpirun initialization.

Remove resource limits for controller manager and node manager

---

controllers/nnf_workflow_controller_helpers.go

Switch to using seq(1), which works with sh(1).

Use the seq(1) command to loop over nslookup in the init container.

---

controllers/integration_test.go
controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_helpers.go
controllers/nnf_workflow_controller_test.go
controllers/nnfcontainerprofile_helpers.go
controllers/nnfcontainerprofile_test.go

This affected some related functions, so I ended up reworking their function signatures and collecting them in a new nnfcontainerprofile_helpers.go.  The functions that were moved to the new file have  more consistent pinned-versus-notpinned checks now.

Fix and use verifyPinnedContainerProfile() in tests

---

controllers/nnf_workflow_controller_test.go

As the Ginkgo book says, "Declare in container nodes, initialize in setup nodes".
I was stumped by why this test wasn't failing.  When I corrected the declare-before-initialize, it became more clear.

Fix a negative NnfContainerProfile test

---

controllers/nnf_workflow_controller.go
controllers/nnf_workflow_controller_container_helpers.go
controllers/nnf_workflow_controller_helpers.go

`containerHandler()` was much too large. This change moves all of the underlying User Container code into it's own helper file. To reduce the number of function parameters (e.g. workflow, profile, ctx) passed into these functions, a new struct was added so that the helper functions could make use it.
Also renamed it to `userContainerHandler()`.

Refactored containerHandler()

---

api/v1alpha1/nnfcontainerprofile_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
controllers/nnf_workflow_controller_test.go
controllers/nnfcontainerprofile_helpers.go

Add an optional UserID/GroupID field to NnfContainerProfileData.  If either of these is specified, then the chosen container profile must match the user ID or group ID specified in the workflow resource that references the profile.
Add tests.

Allow NnfContainerProfiles to be restricted to a UserID/GroupID

---

api/v1alpha1/nnfcontainerprofile_types.go
api/v1alpha1/nnfcontainerprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
controllers/nnf_workflow_controller_container_helpers.go

On LLNL systems, the host's default capabilities are different than HPE systems due to the difference in container runtime and also configuration of those runtimes.
This change drops all capabilities and then adds in the required ones to ensure mpirun can access the worker pods.
Additionally, fix some bugs in the MPISpec of the NnfContainerProfile:
- Don't allow NnfContainerProfile Data to be empty, it's required
- Added check to ensure MPISpec is defined
- Added checks to ensure launcher/worker are defined in the MPISpec
Tested capabilities by:
- Drop ALL capabilities without the specific Adds (and failing)
- Then adding in the specific Adds (and passing)

Containers: Add specific linux capabilities for MPI workers

---

api/v1alpha1/nnfstorageprofile_types.go
api/v1alpha1/nnfstorageprofile_webhook.go
api/v1alpha1/nnfstorageprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
controllers/directivebreakdown_controller.go
controllers/directivebreakdown_controller_test.go
controllers/nnf_access_controller_test.go

Create an option in the Lustre section of the storage profile to only create an MGT. This option will be used by admins to create a pool of MGTs that can be used as external MGTs for other Lustre file systems.

github-83: Add standaloneMgt option to StorageProfile

---

controllers/nnf_workflow_controller_container_helpers.go
go.mod
go.sum
vendor/go.openly.dev/pointy/.gitignore
vendor/go.openly.dev/pointy/LICENSE
vendor/go.openly.dev/pointy/README.md
vendor/go.openly.dev/pointy/comparison.go
vendor/go.openly.dev/pointy/pointy.go
vendor/modules.txt

There is an intermittent issue where mpirun cannot contact the workers even though nslookup can successfully resolve their DNS hostnames in the Init Container. This is seen somewhat infrequently, but has happened enough. The end result causes the user containers to restart (if restartLimit > 0), and it always seems to work on the second try.
This seems to solve the issue by using the Init Continer to use mpirun to contact the workers and just get their hostnames. This replaces the use of nslookup and ensures that mpirun can be successful on the launcher. To support this, the Init Container must run as the given UID/GID rather than root.
It also speeds up container start times as we only need to run 1 Init Container for all of the workers rather than an Init Container for each worker.
I …

Containers: Fix mpirun issue where it cannot contact the workers

---

controllers/nnf_workflow_controller_helpers.go
go.mod
go.sum
vendor/github.com/HewlettPackard/dws/api/v1alpha2/resource_error.go
vendor/modules.txt

Use the GetUserMessage() receiver function when getting the user message for a resource error. This will properly prefix the message with the error type.

Use GetUserMessage() for resource errors

---

Makefile
config/craystack/kustomization.yaml
config/default/kustomization.yaml
config/dp0/kustomization.yaml
config/kind/kustomization.yaml
config/top/kustomization.yaml

This is the version that is installed by the current kubebuilder, v3.12.0. There will be a deprecation warning about patchesStrategicMerge, but this can be ignored.  This warning is tracked in kubebuilder issue #3539.

Update to kustomize v5.1.1

---

api/v1alpha1/webhook_suite_test.go
config/default/manager_auth_proxy_patch.yaml

These are updates from the latest kubebuilder, v3.12.0.

Update kube-rbac-proxy to 0.14.1 and k8s.io/api/admission

---

api/v1alpha1/nnfstorageprofile_types.go
api/v1alpha1/nnfstorageprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml

1GiB is to small to create a zpool when it is divided across 16 drives.

Use 5GiB as the default size for an MGT

---

.gitignore
Makefile
config/manager/kustomization.yaml
deploy.sh
hack/make-kustomization.sh

Avoid editing config/manager/kustomization.yaml to set the image tag.  This causes git to consider the workarea to be dirty, so two consecutive deploys from a workarea that has no other changes will result in the second deploy looking for an image with a "-dirty" tag.
Instead, from the makefile we create a throw-away, and untracked, overlay that will be used to set the image tag.

Dynamically create an overlay for the image tag

---

api/v1alpha1/nnf_datamovement_types.go
config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml
config/dws/nnf-ruleset.yaml
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_test.go

- copy_in/out directives now take a profile=foo argument
- Added profile to NnfDataMovement.Spec
- Uses 'default' profile when not supplied

Add profile argument to copy_in/copy_out directives

---

Makefile
config/examples-htx/kustomization.yaml
config/examples-htx/nnfstorageprofile_patch.yaml

In order to support system-specific storage profiles, we need to add an
overlay based on top of the examples (storage + container profiles)
config.

Add examples-htx overlay

---

api/v1alpha1/workflow_helpers.go
go.mod
go.sum
internal/controller/filesystem_helpers.go
internal/controller/nnf_access_controller.go
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_storage_controller.go
internal/controller/nnf_workflow_controller_helpers.go
pkg/filesystem/kind.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/owner_labels.go
vendor/modules.txt

This is needed for persistent local file systems. The workflow mounting the persistent file system will have a different UID than the workflow that made the file system. Use the owner UID instead (NnfStorage) since that UID will be consistent for the lifetime of the persistent file system.
Also, don't set the file system permissions on ClientMounts in Kind. This will be enabled later when file systems are better mocked out in the kind environment.

Use owner UID instead of workflow UID for VG name

---

internal/controller/nnf_node_block_storage_controller.go

A successful StoragePool or StorageGroup create was causing the NnfNodeBlockStorage reconciler to exit. Another reconcile was queued to finish any remaining work. This is fine for a single allocation on a Rabbit, but with 16 allocations it was slow. It caused the "nvme list" command to run many more times than necessary. 16 storage allocations are now 90s faster.

Batch NnfNodeBlockStorage work into a single reconcile

---

deploy.sh

If a pod is on a host that cannot be reached, then any attempt to delete the namespace will hang.  So change this to preserve the namespace and leave that pod for k8s to cleanup when it can.

Preserve the service namespace during undeploy

---

config/examples/nnf_v1alpha1_nnfstorageprofile.yaml

This was inadvertently changed from true to false in a recent change.
While the impact is low, this does change the established behavior when
deploying to simple systems like Kind.

Revert combinedMgtMdt in placeholder storage profile

---

internal/controller/nnf_systemconfiguration_controller.go

Do not delete the compute namespaces when the SystemConfiguration resource is deleted.

Preserve the compute namespaces during undeploy

---

internal/controller/nnf_access_controller.go
internal/controller/nnf_access_controller_test.go
internal/controller/nnf_workflow_controller.go

Use unique index mount directories that consist of
`<namespace>-<index>`. These unique directories guard against potential
data loss when doing data movement operations. Having the namespace
(i.e. rabbit name) included in the mount path ensures that these
individual compute mount points (index mount directories) are always
unique.
For example, on a 2 rabbit job with 1 compute node each, you would see
the following directories across the 2 rabbits:
/mnt/nnf/7b5dda61-9d91-4b50-a0d3-f863d0aac25b-0/rabbit-node-1-0
/mnt/nnf/7b5dda61-9d91-4b50-a0d3-f863d0aac25b-0/rabbit-node-2-0
If you did not include the namespace, then the paths would be:
/mnt/nnf/7b5dda61-9d91-4b50-a0d3-f863d0aac25b-0/0
/mnt/nnf/7b5dda61-9d91-4b50-a0d3-f863d0aac25b-0/0
On a copy_out directive, if the user specifies the …

Add namespace to index mount directories to avoid DM collision

---

pkg/blockdevice/zpool.go

Tested by:
1. Update the `zpoolCreate` options for mdt in the nnfstorageprofile to include
bad options
2. Without this change, setup will hang on the create. Transition to
teardown and it will also hang since it can't remove the pool that
doesn't exist.
3. With this change, teardown will complete since destroy has nothing to
remove.

zpool destroy: return success if the pool doesn't exist

---

internal/controller/nnf_node_controller.go

The metric should have been in Reconcile(), but was mistakenly placed in Start().

Fix misplaced NnfNodeReconcilesTotal

---

deploy.sh

If a tool is not found, such as yq in the middle of a pipeline, then we want the script to fail.
Also quiet some shellcheck warnings.

Harden deploy.sh

---

config/manager/manager.yaml
pkg/blockdevice/lvm.go

nnf-node-storage controller calls `wipefs` to determine whether a filesystem has been created on a logical volume (lv). The logical volume must first be activated for it to appear in the `/dev/mapper` directory which is where `wipefs` looks for its device. The time it takes for the activate to start and the device to appear in the `/dev/mapper` directory can be a bit longer than the time it takes for the reconciler to `activate` then `wipefs` the logical volume.
This change adds a retry loop around the `wipefs` command to retry at 1 second intervals for a total of 10 seconds before failing the `wipefs` command.

Retry failing wipefs to give mapper device time to appear

---

go.mod
go.sum
internal/controller/nnf_systemconfiguration_controller.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/systemconfiguration_types.go
vendor/modules.txt

I tested this change on the texas system and verified that external compute node: `texas-lustre` was included in the workflow with the following integration test:
```shell
nnf-integration-test# ginkgo run --label-filter="external_lustre" .
```

Include external computes in the map of compute node names

---

config/manager/manager.yaml
pkg/blockdevice/lvm.go

It turns out that any actions after the vgactivate have to wait for the vg device to appear in the /dev/mapper directory. Insert a wait for the device to appear in mapper into the activate action.
This change has been trialed on a previously failing system with success.

After activate, wait for the vg to appear in /dev/mapper directory

---

cmd/main.go
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_node_block_storage_controller.go
internal/controller/nnf_node_controller.go
internal/controller/nnf_node_ec_data_controller.go
internal/controller/nnf_node_storage_controller.go
internal/controller/suite_test.go

Add channel semaphores to serialize the startup of the NLC reconcilers that are using EC.  Add locks to each reconciler to block its Reconcile() until it has completed its Start().

Serialize the NLC reconcilers

---

config/examples/nnf_v1alpha1_nnfstorageprofile.yaml

The NnfStorageProfile/placeholder resource is meant to be an example resource and should not be marked as default.

Remove the default flag from NnfStorageProfile/placeholder

---

.vscode/launch.json
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_helpers.go
internal/controller/nnf_workflow_controller_helpers_test.go

- Moved `getRabbitRelativePath` to its own function for testability
- `getRabbitRelativePath` now preserves trailing slashes for the path
- Fixed issue with `splitStagingArgumentIntoNameAndPath` assuming a
leading slash
- Added unit tests for `splitStagingArgumentIntoNameAndPath` and `getRabbitRelativePath`

Fix trailing slash issues with Data Movement

---

internal/controller/nnf_storage_controller.go

Ensure NnfNodeBlockStorages for lustre have a capacity of at least 4GB

---

internal/controller/nnf_node_ec_data_controller.go
pkg/blockdevice/zpool.go

This ensures that any existing pools are imported and present after a reboot of the rabbit node.
Tested by:
1. Create lustre workflow and transition to PostRun
2. Reboot the rabbit-node prior to Teardown
3. Once rebooted, verify that zool list includes pools
4. Verify log contains "Imported all available zpools"
Another test:
1. Do step 1 from above.
2. Transition to Teardown and then very quickly reboot the rabbit node (`ssh rabbit-node-2 reboot`).
3. Once rabbit node reboots, workflow will transition to Teardown complete.
4. Verify step 4 above.
5. Verify `zpool list` as no pools left.
moved import to NnfNodeECData.Start()

Add `zpool import` on Node EC Data controller startup

---

config/manager/manager.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml

This allows us to separate system-level vs node-level traffic to the apiserver with "API Priority and Fairness" queues.

Create a separate ServiceAccount for the node-level controller

---

internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_helpers.go

The NNfAccess isn't created yet, so the existing code reported this as an error. This error quickly resolves itself, but flux sees that the workflow went to error state (intermittently) and then immediately transitions to Teardown.
Add a requeue if the NnfAccess isn't found. Also, expand on the error message and report it to the user.

Containers: Requeue to wait for NnfAccess to appear

---

internal/controller/directivebreakdown_controller.go
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_helpers.go

- A missing pinned profile is now transient (major error)
- Fixed an issue with userContainerHandler() and its subroutines accidentally masking lower severity errors. Everything was being reported as Fatal at the top level.
Both issues were causing flux to see the fatal errors and immediately transition to Teardown.

Address Transient Error issues

---

internal/controller/filesystem_helpers.go

Ran into this when canceling a bunch of flux jobs repeatedly. Something got wedged in regards to persistent storage and a panic occurs. This guards against the two index out of range panics.

filesystem-helpers: guard against empty status allocations

---

cmd/main.go

Configure the time the same way we do for other services. This allows both the NLC and SLC controllers to agree on using UTC, rather than having one local and the other UTC.

Configure time for UTC.

---

.dockerignore
.github/workflows/rpm_build.yml
.gitignore
Dockerfile.rpmbuild
Makefile
clientmount.spec

Build the daemon in an environment defined by a Dockerfile, and build it with the same environment whether it's built locally or within a workflow.
Using `make build-daemon` will build the daemon locally as always and continue to drop it into the local bin/ directory.
Using `make build-daemon-rpm` will build the daemon within the container environment and will drop the resulting rpm in a local rpm/ directory.
In tests so far, this tends to cut the build time within the workflow to about 1/3 of the time that we've seen in the past.

Daemon RPM build rework

---

cmd/main.go
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_node_block_storage_controller.go
internal/controller/nnf_node_controller.go
internal/controller/nnf_node_ec_data_controller.go
internal/controller/nnf_node_storage_controller.go
internal/controller/suite_test.go
mount-daemon/main.go

Add channel semaphores to serialize the startup of the NLC reconcilers that are using EC.  Add locks to each reconciler to block its Reconcile() until it has completed its Start().
This is a rewrite of an earlier version, this time using close() on the channel rather than leaving the channels open.

Serialize the NLC reconcilers, take 2

---

go.mod
go.sum
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
vendor/modules.txt

Avoid doing a divide-by-zero and panicing the process.

Handle empty capacity when a drive cannot be found.

---

config/crd/bases/nnf.cray.hpe.com_nnfaccesses.yaml
config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodeblockstorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodestorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorages.yaml
go.mod
go.sum
internal/controller/nnf_access_controller.go
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_storage_controller.go
internal/controller/nnfstorageprofile_helpers.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/resource_error.go
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_clientmounts.yaml
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_directivebreakdowns.yaml
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_persistentstorageinstances.yaml
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_servers.yaml
vendor/modules.txt

Errors weren't being properly set in the NnfNodeStorage, NnfNodeBlockStorage, and ClientMount resources in some instances. Make sure that the error is always returned from the main Reconcile() function so that it gets picked up by SetResourceErrorAndLog()
Also, add a fatal error if a user specified NnfStorageProfile isn't found.

Fix error reporting from NnfNodeStorage and NnfNodeBlockStorage

---

api/v1alpha1/nnf_node_block_storage_types.go
api/v1alpha1/nnf_node_storage_types.go
api/v1alpha1/nnf_storage_types.go
api/v1alpha1/nnfstorageprofile_types.go
cmd/main.go
config/crd/bases/nnf.cray.hpe.com_nnfnodeblockstorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodestorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorages.yaml
config/examples/nnf_v1alpha1_nnfstorageprofile.yaml
internal/controller/filesystem_helpers.go
internal/controller/nnf_access_controller.go
internal/controller/nnf_access_controller_test.go
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_node_block_storage_controller.go
internal/controller/nnf_node_storage_controller.go
internal/controller/nnf_storage_controller.go
internal/controller/nnf_workflow_controller_helpers.go
internal/controller/nnfstorageprofile_test.go
mount-daemon/main.go
pkg/blockdevice/blockdevice.go
pkg/blockdevice/lvm.go
pkg/blockdevice/lvm/logical_volumes.go
pkg/blockdevice/lvm/vgs.go
pkg/blockdevice/mock.go
pkg/blockdevice/zpool.go
pkg/filesystem/lustre.go
pkg/filesystem/simple.go

This commit adds a new option, sharedVg, in the NnfStorageProfile for allocations backed by an LVM logical volume. This option allows allocations on a Rabbit node that are part of the same workflow to share a volume group. This reduces the overhead of creating allocations and greatly speeds up the Setup and Teardown phases of the workflow.
This commit also changes the way locking is done with lvmlockd. Previously, when the LV was not needed on a node, the LV was deactivated and the VG lockspace was stopped. Now, only the LV is deactivated in most situations. The VG lockspace is only stopped when a node is completely done with a VG and it won't be activated again.

Add option for a single shared VG per Rabbit per workflow

---

internal/controller/nnf_node_block_storage_controller.go
internal/controller/nnf_storage_controller.go

The allocation teardown code was checking whether a storage pool ID was listed in the status section of the NnfNodeBlockStorage before trying to delete it. If there was an issue saving the storage pool ID (e.g., conflict), then we can strand NVMe namespaces on the Rabbit. Always try to delete storage pools for every known index and treat "not found" errors as a success.
Also, fix an error with the NnfStorage deletion code where the child objects (NnfNodeStorage and NnfNodeBlockStorage) don't get deleted if they currently have an error.

Don't check status when deleting storage pools

---

.github/workflows/rpm_build.yml

It wasn't doing a push on merge to the releases/v0 branch. However, other workflows that simply have "on: push" were building on that merge. So, let's try that.

Do rpm build on all pushes

---

Makefile
hack/make-kustomization.sh

Add component/version labels to each resource in the manifest. If run locally the labels will be:
app.kubernetes.io/component: nnf-sos
app.kubernetes.io/version: <git-version-gen>
If run from nnf-deploy's "make manifests" the labels will be:
app.kubernetes.io/component: nnf-sos
app.kubernetes.io/version: <nnf-sos's git-version-gen>
app.kubernetes.io/part-of: nnf
app.kubernetes.io/nnf-version: <nnf-deploy's git-version-gen>

Add version labels to release manifest items

---

internal/controller/filesystem_helpers.go

The zpool name was not using the starting index provided in the NnfNodeStorage when finding the index for the zpool. This results in an inconsistency between the zpool name and the OST/MDT index.

Keep zpool name consistent with OST/MDT index

---

internal/controller/nnf_workflow_controller_helpers.go

If the MGS address specified for an external MGS uses an LNet that ends with index "0", trim the "0" off the address. Lustre aliases the 0 index with no index, and it uses no index in the "mount" command output.
For example:
10.1.1.113@tcp0 -> 10.1.1.113@tcp

Use alias for LNet index 0

---

config/rbac/kustomization.yaml
config/rbac/workload_manager_nnf_role.yaml

When access to NNF resources is desired, then the WLM would use this ClusterRole rather than the one provided by DWS.

Add a WLM ClusterRole that can also access some NNF resources

---

internal/controller/dws_storage_controller.go
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_helpers.go

The Storage reconciler wasn't running when the k8s node resource changed. This is because the enqueuing function wasn't specifying the namespace in the namespacedname struct.
Also, fix the Requeue() function so that it specifies a requeue in the result. In the delete path, the Requeue=true result doesn't always result in a requeue. Use RequeueAfter=1sec instead. This was only an issue when the workflow was deleted without waiting for teardown to complete first. Teardown normally removes the container and port resources that were causing the issue.

Get missing events from k8s Node resource

---

internal/controller/nnf_workflow_controller_helpers.go

When choosing an MGS from the persistent storages tagged with the pool label, it's possible to panic the nnf-controller-manager if the persistent storage list is empty.

Check for empty list when choosing an MGS

---

api/v1alpha1/nnf_datamovement_types.go
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_test.go

There currently is not a specific determination on where an
NnfDataMovement resource is created.
This label is used by the Copy Offload API to record the compute node,
but that's it. Add a function to add the label and use `copy_in` or
`copy_out` for the value.

Add DataMovementInitiatorLabel to copy_in/copy_out DMs

---

go.mod
go.sum
internal/controller/dws_storage_controller.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/resource.go
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_storages.yaml
vendor/modules.txt

Specifically, if any cray.nnf.node.drain* taint is applied to the node then
mark the corresponding Storage resource as "Drained". The WLM will see this
and will stop scheduling work on this node.
Restore the Storage resource to "Ready" after the taint has been removed.

Mark Storage resource as drained if its node is tainted

---

cmd/main.go

The rest.Config QPS and burst values control client side throttling. Expose these values through environment variables so they can be tuned.

Add environment variables to set QPS and burst values

---

internal/controller/filesystem_helpers.go

We've had situations where the NnfNodeStorage reads the NnfNodeBlockStorage device list and gets an empty list of devices. This could be caused by a stale NnfNodeBlockStorage resource in the cache. The status.ready flag in the NnfNodeBlockStorage won't be set until everything is filled in. Check that flag before reading any values.

Check NnfNodeBlockStorage is ready before reading device list

---

PROJECT

This file is used by the crd bumper tool.

Fix NnfAccess version in ./PROJECT

---

api/v1alpha1/nnf_datamovement_types.go
api/v1alpha1/nnfdatamovementprofile_types.go
config/crd/bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml
config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml

This allows users to add extra parameters to mpirun (e.g. -N, -n) for an
individual data movement.

Add mpirunOptions to NnfDataMovementConfig

---

internal/controller/integration_test.go
internal/controller/nnf_access_controller_test.go
internal/controller/nnf_systemconfiguration_controller.go
internal/controller/nnf_systemconfiguration_controller_test.go
internal/controller/nnf_workflow_controller_container_helpers.go
internal/controller/nnfsystemstorage_controller_test.go

So the crd-bumper tool can find these references.

Use "nnfv1alpha1" to refer to the api/v1alpha1 libs

---

cmd/main.go

This is where kubebuilder should place new calls to SetupWebhookWithManager().

Move kubebuilder:scaffold:builder for new webhooks

---

api/v1alpha1/nnfnodestorage_types.go
api/v1alpha1/nnfstorage_types.go
api/v1alpha1/nnfsystemstorage_types.go
config/crd/bases/nnf.cray.hpe.com_nnfnodestorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfsystemstorages.yaml

For the kubebuilder:default to work, you have to first allow the field to be empty.

Allow empty FStype in NnfNodeStorageSpec

---

Makefile

Various other tools get caught in this dir with its big data files and it's a nuisance.

Clean up internal/controller/nnf.db immediately after make test

---

crd-bumper.yaml

Tell crd-bumper about the Go code in the mount-daemon/ directory.

Specify a repo-specific config for crd-bumper

---

config/examples-htx/nnfstorageprofile_patch.yaml
config/examples/kustomization.yaml
config/examples/nnf_nnfcontainerprofiles.yaml
config/examples/nnf_nnfdatamovementprofile.yaml
config/examples/nnf_nnfstorageprofile.yaml

Argocd is reporting them as OutOfSync because they are in the gitops repo as v1alpha1 but when argocd queries them it gets back v1alpha2.

Move example resources to v1alpha2

---

cmd/main.go
internal/controller/nnf_access_controller.go
internal/controller/nnf_node_block_storage_controller.go
internal/controller/nnf_node_controller.go
internal/controller/suite_test.go

Use the GenericEvent source to trigger the event through a channel. Update the NnfNode reconciler to use the same method.
Also, change the NnfAccess reconciler to wait for the StorageGroups to be created on the Rabbit before creating the ClientMount resources.

Trigger reconcile for NnfNodeBlockStorage from nnf-ec events

---

config/manager/manager.yaml
internal/controller/nnf_access_controller.go
internal/controller/nnf_storage_controller.go

The ClientMount, NnfNodeStorage, and NnfNodeBlockStorage resources are fanned out to the Rabbit and compute nodes. If the correct controllers aren't running on one or more of those nodes, then the workflow will not progress but won't give an error. Add an optional timeout that checks whether the controller on the Rabbit/compute node has added its finalizer within a configurable amount of time. If the finalizer hasn't been added, then return an error.

Add timeout when creating fan-out child resources

---

config/dp0/manager_volumes_patch.yaml
config/kind/manager_volumes_patch.yaml
internal/controller/nnf_node_ec_data_controller.go

Mount /localdisk (the M.2) into the nnf-node-manager pods. Use the default database in nnf-ec (badger) and change the working directory of the container to /localdisk so the database file is created in the correct spot.

Use a file based database for nnf-ec

---

.vscode/launch.json
internal/controller/nnf_clientmount_controller.go
internal/controller/nnf_clientmount_controller_test.go

User jobs currently do not have a way to retrieve the Servers resource
for a workflow. Access to the servers resource can provide lustre
information, such as which rabbit nodes are being used for MDT/OSTs.
This creates a file (`./.nnf-servers.json`) at the root of the lustre
filesystem that contains the servers resource. It can then be parsed
using `jq` to retrieve the pertinent information.
Example:
```
flux run -N1 -l --setattr=dw="#DW jobdw name=blake type=xfs capacity=500GB" bash -c "cat \$DW_JOB_blake/.nnf-servers.json | jq '.spec.allocationSets[] | .label,.storage'"
```

Create nnf-servers file for lustre filesystems

---

pkg/blockdevice/lvm/volume_groups.go

Do not print the always-nil 'err' value when we timeout while waiting for a VG to appear.

Nil err message after waiting for VG

---

internal/controller/nnf_access_controller.go

The NnfNodeBlockStorage resource is not owned by the NnfAccess, so the NnfAccess won't be requeued after the client cache updates.

Requeue in NnfAccess after NnfNodeBlockStorage conflict

---

internal/controller/nnf_access_controller.go

This was a workaround to account for creating multiple OSTs in an
unorthodox manner in the Servers resource. Flux won't create multiple
allocation sets on a single rabbit, but rather use the count when there
are multiple allocations on a single rabbit.
This workaround causes a bug and is not needed.

Fix NnfAccess ClientMount count

---

api/v1alpha4/nnfstorageprofile_types.go
api/v1alpha4/nnfstorageprofile_webhook.go
api/v1alpha4/nnfstorageprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
config/manager/kustomization.yaml

Release v0.1.18

---

go.mod
go.sum
internal/controller/nnf_node_block_storage_controller.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/allocation_policy.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nnf/manager.go
vendor/github.com/NearNodeFlash/nnf-ec/pkg/manager-nvme/manager.go
vendor/modules.txt

Vendor in nnf-ec changes to implement the `strict` allocation compliance policy, and then select that compliance policy for use with nnf-node-block-storage devices.

Select strict allocation compliance to guarantee equally sized namespaces on each drive

---

config/examples/nnf_nnfcontainerprofiles.yaml

The `latest` tag no longer exists for this image. Use `master` instead.

Fix nnf-container-example image tag in container profile

---

api/v1alpha3/nnfaccess_types.go
api/v1alpha3/nnfcontainerprofile_types.go
api/v1alpha3/nnfdatamovement_types.go
api/v1alpha3/nnfdatamovementmanager_types.go
api/v1alpha3/nnfdatamovementprofile_types.go
api/v1alpha3/nnflustremgt_types.go
api/v1alpha3/nnfnode_types.go
api/v1alpha3/nnfnodeblockstorage_types.go
api/v1alpha3/nnfnodeecdata_types.go
api/v1alpha3/nnfnodestorage_types.go
api/v1alpha3/nnfportmanager_types.go
api/v1alpha3/nnfstorage_types.go
api/v1alpha3/nnfstorageprofile_types.go
api/v1alpha3/nnfsystemstorage_types.go
config/crd/bases/nnf.cray.hpe.com_nnfaccesses.yaml
config/crd/bases/nnf.cray.hpe.com_nnfdatamovementmanagers.yaml
config/crd/bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml
config/crd/bases/nnf.cray.hpe.com_nnfdatamovements.yaml
config/crd/bases/nnf.cray.hpe.com_nnflustremgts.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodeblockstorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodeecdata.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodes.yaml
config/crd/bases/nnf.cray.hpe.com_nnfnodestorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfportmanagers.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
config/crd/bases/nnf.cray.hpe.com_nnfstorages.yaml
config/crd/bases/nnf.cray.hpe.com_nnfsystemstorages.yaml
internal/controller/conversion_test.go

Mark the v1alpha3 API as unserved.
ACTION: Address the ACTION comments in internal/controller/conversion_test.go.
ACTION: Begin by running "make vet". Repair any issues that it finds.
Then run "make test" and continue repairing issues until the tests
pass.

CRDBUMPER-unserve-api

---

internal/controller/nnf_clientmount_controller.go
pkg/blockdevice/lvm/logical_volumes.go

If the block debice fails to activate in the ClientMount reconciler, rescan for NVMe devices and let the reconciler retry. Some compute nodes have trouble automatically finding the namespaces after a storage group is created on the Rabbit.

Rescan NVMe devices in ClientMount reconciler

---

pkg/blockdevice/nvme/nvme.go

Passing a list of devices the `nvme ns-rescan` rescans only the first device in the list.
Instead, rescan each /dev/nvme<id> individually.

Rescan each nvme device individually

---

internal/controller/nnf_clientmount_controller.go
pkg/blockdevice/nvme/nvme.go

Rescan devices when the ClientMount resource is deleted to make sure we pick up the removal of the NVMe namespaces. Also, print a log message anytime the NVMe rescan results in a change to the number of NVMe namespaces in /dev.

Rescan devices on ClientMount deletion

---

internal/controller/nnf_workflow_controller_helpers.go

Allow the JobID from the workflow to be used in commands through the $JOBID variable.

Add JOBID command variable

---

internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_container_helpers.go
internal/controller/nnf_workflow_controller_helpers.go
internal/controller/nnf_workflow_controller_test.go

This adds a few pieces to support using mpi-operator for the new Copy Offload API.
Most notably is adding the `NNF_COPY_OFFLOAD_SERVER` environment variable which tells the compute nodes how to contact the Copy Offload Server that is hosting the API on one of the rabbit nodes allocated to the workflow.

Copy Offload API: Support changes to using mpi-operator

---

config/examples/nnf_nnfstorageprofile.yaml
internal/controller/nnf_node_block_storage_controller.go

Add a log message that includes "vgs" and "zfs list" output after getting and insufficient capacity error. Also, add the job ID as a tag on the VG and a user property on the ZFS dataset.
Unfortunately, our version of "zfs list" does not support json output.

Add debug output for insufficient capacity error

---

internal/controller/nnf_workflow_controller_container_helpers.go
internal/controller/nnf_workflow_controller_helpers.go

Previously, the implementation did not account for multiple containers in a PodSpec, leading to issues where the same port was mapped across multiple containers, which is invalid.
This update ensures that numPorts ports are opened for each container in the PodSpec. For non-MPI containers, this applies to all containers. For MPI containers, only the Launcher containers are assigned ports, as the workers are accessed via mpirun through the Launcher.
The port numbers are exposed via the NNF_CONTAINER_PORTS environment variable. Additionally, new environment variables are created for each container using the container name, e.g.,
NNF_CONTAINER_PORTS_<container_name>.
This change also fixes issues related to supporting multiple containers and resolves a problem with the subdomain environment …

Containers: Open numPorts host ports for each container

---

internal/controller/nnf_workflow_controller_container_helpers.go

Labels are applied to the MPIJob resource, but they don't make it down
to the pods themselves. This adds the labels directly to the pods, being
careful of the current ownership.

Ensure workflow labels make it to mpi launcher and workers

---

api/v1alpha7/nnfcontainerprofile_webhook.go
api/v1alpha7/nnfcontainerprofile_webhook_test.go

Ensure that container names that indicate copy offload have the correct service account and also ensure the profile is using MPI.

Container profiles: Add copy offload checks

---

api/v1alpha7/nnfdatamovementprofile_types.go
api/v1alpha7/nnfdatamovementprofile_webhook.go
api/v1alpha7/nnfdatamovementprofile_webhook_test.go
config/crd/bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml

Make sure that the data movement commands contain the required $VAR in the command string.
Only do this when the expected command is found (e.g. dcp, mkdir) first. This allows for open configuration of the commands for testing/debugging purposes. For example, using `sleep 5` instead of an actual `dcp` command. Otherwise the validation would fail.

DM Profile: Add $VAR checks for commands in webhook

---

internal/controller/integration_test.go
internal/controller/nnf_workflow_controller.go
internal/controller/nnf_workflow_controller_container_helpers.go
internal/controller/nnf_workflow_controller_helpers.go
internal/controller/nnf_workflow_controller_test.go

During Proposal state, if the Workflow directive specifies copy-offload or user-container-auth, check for the system "nnf-dm-usercontainer-client-tls" secret.

Verify user container TLS secret during Proposal

---

config/dp0/manager_volumes_patch.yaml

The nnf-node-manager pod needs the /run directory from the host mounted into the container for lvmlockd. If there are nnf managed mounts in /mnt/nnf, the Rabbit code gets confused when the pod is restarted. This is because the root file system for the pod ends up in /run. For example:
/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/b154194bfffc1990354a28ba5f290b22bff89f46f3c8228187749a259be38765/rootfs
Any NNF managed mounts will show up in that root file system as well as in /mnt/nnf. When an unmount is done on the /mnt/nnf path, the mount under the /run path still exists even though on the host it is gone. This results in the file system not getting fully unmounted (since there is still a mount in the container), and the Rabbit software unable to find a file system to unmount. …

Add HostToContainer mount propagation for /run

---

internal/controller/nnf_node_storage_controller.go
internal/controller/nnf_storage_controller.go

Allow the file system creation and NVMe namespace creation to complete in parallel across different Rabbits by creating the NnfNodeStorage and NnfNodeBlockStorage at the same time. The NnfNodeStorage controller will wait for the NnfNodeBlockStorage to be marked as Ready before attempting to make the file system

Create NnfNodeStorage before NnfNodeBlockStorage is ready

---

internal/controller/nnf_node_block_storage_controller.go

The NnfNodeBlockStorage and NnfNodeStorage resources both get marked for deletion at the same time. This can cause an issue if the nnf-node-manager restarts before the NnfNodeStorage is fully deleted. The NnfNodeStorage controller relies on the NnfNodeBlockStorage keeping the status section up to date with the latest /dev paths for the NVMe namespaces.
This change forces the NnfNodeBlockStorage controller to skip the deletion path code until the NnfNodeStorage has finished deleting.

Keep updating NnfNodeBlockStorage /dev until NnfNodeStorage is deleted

---

config/examples/nnf_nnfcontainerprofiles.yaml
internal/controller/nnf_workflow_controller_container_helpers.go
internal/controller/nnf_workflow_controller_helpers.go

Any long-running user container (e.g., copy offload) that does not shut down on its own will get stuck in PostRun until the `postRunTimeoutSeconds` timeout is hit. This results in an error since the containers did not finish in the PostRun state before the timeout.
This change adds a shutdown request to the PostRun logic for user containers. The long-running container **must** implement an HTTPS server that accepts a `POST` to the `/shutdown` endpoint. This allows the user container to shut down gracefully and return success, allowing PostRun to proceed.
If the shutdown request fails, the workflow continues. In fact, we expect it to eventually fail since the user container will shut down and no longer respond. Any errors are logged and do not affect the workflow outcome. If there are …

User Containers: Send `/shutdown` POST to long-running containers

---

internal/controller/nnf_access_controller.go

When the NnfAccess resource is deleted, remove the access entry in the NnfNodeBlockStorage (resulting in the StorageGroup deletion), but don't wait to see if it succeeds. The NnfAccesses are deleted in Teardown when everything is getting deleted anyway. This allows the NnfStorage to start deleting even if the StorageGroup can't clean up on one of more of the Rabbits.

Don't check for block device accesses success after removal

---

go.mod
go.sum
internal/controller/dws_servers_controller.go
internal/controller/nnf_access_controller.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha2/zz_generated.conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha3/conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha3/zz_generated.conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha4/conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha4/zz_generated.conversion.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha5/servers_types.go
vendor/github.com/DataWorkflowServices/dws/api/v1alpha5/workflow_types.go
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_servers.yaml
vendor/github.com/DataWorkflowServices/dws/config/crd/bases/dataworkflowservices.github.io_workflows.yaml
vendor/github.com/DataWorkflowServices/dws/controllers/workflow_controller.go
vendor/modules.txt

Use the new "ready" field in the servers resource to indicate the status of the allocations on each Rabbit. Also, have the NnfAccess controller ignore NnfNodeStorages that aren't ready. This is to satisfy the "forceReady" feature in the workflow that can proceed past "Setup" when all the allocations haven't been created.

Update servers resource with allocation ready status

---

cmd/main.go
config/default/manager_auth_proxy_patch.yaml

Add some commandline args to the controller to control the LeaseDuration, RenewDeadline, and RetryPeriod. Adjust the patch that builds the manifest to insert these.

Allow a longer grace time for renewing the leader-election lease.
